name: Laravel deployment
run-name: ${{ github.actor }} is trying to deploy groenevingers.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 
          MYSQL_DATABASE: deployment_db
        ports:
          - 3306:3306
        options: --health-cmd='mysqladmin ping --silent' --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.0'
          extentions: mbstring, bcmath, mysqli
          ini-values: post_max_size=256M, max_execution_time=300
      
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Create .env file
        run: cp .env.example .env
      
      - name: Generate application key
        run: php artisan key:generate

      - name: Run database migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: deployment_db
          DB_USER: root
          DB_PASSWORD:
        run: php artisan migrate --no-interaction --force

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Run linter
        run: vendor/bin/pint

      - name: Build Release (create versioned release)
        if: github.event_name == 'pushed' && startsWith(github.ref, 'refs/tags/')
        run: echo "Creating a new release for version ${GITHUB_REF##*/}"